version: '3.3'

services:
  doxy:
    build: .
    hostname: doxy
    container_name: doxy
    command: doxy -D :53 -H :80 -I :443 -S :1080
    restart: always

    volumes:
      - .:/go/src/github.com/akatrevorjay/doxy
      - /var/run/docker.sock:/run/docker.sock
      - ./ca:/ca

    network_mode: host

    expose:
      # dns
      - 53/udp
      - 53/tcp
      # http
      - 80/tcp
      - 443/tcp
      # socks5h
      - 1080/tcp
