dnsdock:
  build: .
  hostname: dnsdock
  container_name: dnsdock
  command: dnsdock --dns=":53" --http=":80" --alias -v
  #command: dnsdock --dns=":54" --http=":80" --alias -v
  volumes:
    - /var/run/docker.sock:/run/docker.sock
  #net: host
  ports:
    - 172.17.0.0:53:53/udp
    - 172.17.0.0:53:53/tcp
  restart: always
