dnsdock:
  build: .
  hostname: dnsdock
  volumes:
    - /var/run/docker.sock:/run/docker.sock
  #command: -nameserver 192.168.0.1:53 -nameserver 8.8.8.8:53
  #network_mode: host
  #ports:
  #  - 172.17.0.0:53:53/udp
  ##restart: always
